version: 2
registries:
  wire:
    type: nuget-feed
    url: http://168.63.129.16/?comp=versions
    username: user
    password: dummy
  imds:
    type: nuget-feed
    url: http://169.254.169.254/metadata/instance
    username: user
    password: dummy
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    registries:
      - wire
      - imds
